### ISSUE TITLE
broken with current version?

### ISSUE THREAD

**Issue by markfink** [raineorshine/generator-yoga#3]
I came here for a simple generator sample. When I install Yoga using yo version 1.5.0 I get the following:

```bash
? 'Allo Mark! What would you like to do? Yoga

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo yoga

No yoga file found. Proceeding with simple copy.

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__   
 ´   `  |° ´ Y ` 

events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'prompts' of undefined
    at module.exports.generators.Base.extend.prompting (/home/mark/.node/lib/node_modules/generator-yoga/app/index.js:81:40)
    at /home/mark/.node/lib/node_modules/generator-yoga/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
mark@ichikawa:~/devel/bee-do/research/yeoman/exp_yoga$ yo --version
1.5.0
```

**Comment by cdibbs** [comment]
I also get this issue from a clean install of latest yo and generator-yoga.

**Comment by raineorshine** [comment]
Thanks for reporting! Sorry I didn't see this before. I'm working on rehabilitating the repo.

I fixed a couple bugs and released `v2.0.0`. If you ever end up trying it again, let me know if you have any difficulties.
